/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as AuthRouteRouteImport } from './routes/auth/route';
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route';
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index';
import { Route as AuthLoginRouteImport } from './routes/auth/login';
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route';
import { Route as AuthenticatedStaffIndexRouteImport } from './routes/_authenticated/staff/index';
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index';
import { Route as AuthenticatedSettingsMiscRouteImport } from './routes/_authenticated/settings/misc';
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account';

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport
} as any);
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport
} as any);
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute
} as any);
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute
} as any);
const AuthenticatedSettingsRouteRoute = AuthenticatedSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute
} as any);
const AuthenticatedStaffIndexRoute = AuthenticatedStaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => AuthenticatedRouteRoute
} as any);
const AuthenticatedSettingsIndexRoute = AuthenticatedSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedSettingsRouteRoute
} as any);
const AuthenticatedSettingsMiscRoute = AuthenticatedSettingsMiscRouteImport.update({
  id: '/misc',
  path: '/misc',
  getParentRoute: () => AuthenticatedSettingsRouteRoute
} as any);
const AuthenticatedSettingsAccountRoute = AuthenticatedSettingsAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedSettingsRouteRoute
} as any);

export interface FileRoutesByFullPath {
  '/auth': typeof AuthRouteRouteWithChildren;
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren;
  '/auth/login': typeof AuthLoginRoute;
  '/': typeof AuthenticatedIndexRoute;
  '/settings/account': typeof AuthenticatedSettingsAccountRoute;
  '/settings/misc': typeof AuthenticatedSettingsMiscRoute;
  '/settings/': typeof AuthenticatedSettingsIndexRoute;
  '/staff': typeof AuthenticatedStaffIndexRoute;
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRouteRouteWithChildren;
  '/auth/login': typeof AuthLoginRoute;
  '/': typeof AuthenticatedIndexRoute;
  '/settings/account': typeof AuthenticatedSettingsAccountRoute;
  '/settings/misc': typeof AuthenticatedSettingsMiscRoute;
  '/settings': typeof AuthenticatedSettingsIndexRoute;
  '/staff': typeof AuthenticatedStaffIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren;
  '/auth': typeof AuthRouteRouteWithChildren;
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren;
  '/auth/login': typeof AuthLoginRoute;
  '/_authenticated/': typeof AuthenticatedIndexRoute;
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute;
  '/_authenticated/settings/misc': typeof AuthenticatedSettingsMiscRoute;
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute;
  '/_authenticated/staff/': typeof AuthenticatedStaffIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/auth'
    | '/settings'
    | '/auth/login'
    | '/'
    | '/settings/account'
    | '/settings/misc'
    | '/settings/'
    | '/staff';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/auth'
    | '/auth/login'
    | '/'
    | '/settings/account'
    | '/settings/misc'
    | '/settings'
    | '/staff';
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/settings'
    | '/auth/login'
    | '/_authenticated/'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/misc'
    | '/_authenticated/settings/'
    | '/_authenticated/staff/';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren;
  AuthRouteRoute: typeof AuthRouteRouteWithChildren;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth';
      path: '/auth';
      fullPath: '/auth';
      preLoaderRoute: typeof AuthRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_authenticated': {
      id: '/_authenticated';
      path: '';
      fullPath: '';
      preLoaderRoute: typeof AuthenticatedRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_authenticated/': {
      id: '/_authenticated/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof AuthenticatedIndexRouteImport;
      parentRoute: typeof AuthenticatedRouteRoute;
    };
    '/auth/login': {
      id: '/auth/login';
      path: '/login';
      fullPath: '/auth/login';
      preLoaderRoute: typeof AuthLoginRouteImport;
      parentRoute: typeof AuthRouteRoute;
    };
    '/_authenticated/settings': {
      id: '/_authenticated/settings';
      path: '/settings';
      fullPath: '/settings';
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport;
      parentRoute: typeof AuthenticatedRouteRoute;
    };
    '/_authenticated/staff/': {
      id: '/_authenticated/staff/';
      path: '/staff';
      fullPath: '/staff';
      preLoaderRoute: typeof AuthenticatedStaffIndexRouteImport;
      parentRoute: typeof AuthenticatedRouteRoute;
    };
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/';
      path: '/';
      fullPath: '/settings/';
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport;
      parentRoute: typeof AuthenticatedSettingsRouteRoute;
    };
    '/_authenticated/settings/misc': {
      id: '/_authenticated/settings/misc';
      path: '/misc';
      fullPath: '/settings/misc';
      preLoaderRoute: typeof AuthenticatedSettingsMiscRouteImport;
      parentRoute: typeof AuthenticatedSettingsRouteRoute;
    };
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account';
      path: '/account';
      fullPath: '/settings/account';
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport;
      parentRoute: typeof AuthenticatedSettingsRouteRoute;
    };
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute;
  AuthenticatedSettingsMiscRoute: typeof AuthenticatedSettingsMiscRoute;
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute;
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren = {
  AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
  AuthenticatedSettingsMiscRoute: AuthenticatedSettingsMiscRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute
};

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(AuthenticatedSettingsRouteRouteChildren);

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren;
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute;
  AuthenticatedStaffIndexRoute: typeof AuthenticatedStaffIndexRoute;
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedStaffIndexRoute: AuthenticatedStaffIndexRoute
};

const AuthenticatedRouteRouteWithChildren = AuthenticatedRouteRoute._addFileChildren(
  AuthenticatedRouteRouteChildren
);

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute;
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute
};

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(AuthRouteRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
